services:
  # Service Frontend (Nginx Production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: appnote-frontend
    restart: always
    ports:
      - "${INTERNAL_PORT}:80"
    environment:
      - VITE_BACKEND_TARGET=http://backend:3000
    depends_on:
      - backend
    networks:
      - appnote_net

  # Service Backend (Node.js + Prisma)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: appnote-backend
    restart: always
    volumes:
      - ./prisma:/app/prisma # Persistance de la base SQLite
    environment:
      - PORT=3000
      - DATABASE_URL=file:/app/prisma/dev.db
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_TRUSTED_ORIGINS=${BETTER_AUTH_TRUSTED_ORIGINS}
    networks:
      - appnote_net
    # Le backend reste interne au réseau Docker (accessible via http://backend:3000)

networks:
  appnote_net:
    driver: bridge
